# Generated by Django 4.2.1 on 2023-07-13 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=255)),
                ("password", models.CharField(max_length=50)),
                ("ifLogged", models.BooleanField(default=False)),
                ("token", models.CharField(default="", max_length=500, null=True)),
            ],
        ),
    ]
